export const successOperations = [
  "search",
  "read",
  "status",
  "probe_embedding",
  "probe_vector",
] as const;

export const failureCodes = [
  "INVALID_REQUEST",
  "DENIED",
  "UNAVAILABLE",
  "TIMEOUT",
  "ABORTED",
  "LAUNCH_FAILED",
  "NONZERO_EXIT",
  "MALFORMED_OUTPUT",
  "OUTPUT_LIMIT",
] as const;

export const requiredFixtureNames = [
  "search-source-file-line",
  "search-empty-result",
  "search-shared-visibility",
  "search-private-visibility",
  "search-valid-session-identity",
  "search-archived-session-identity",
  "read-signed-skw-path",
  "status-ready",
  "probe-embedding-available",
  "probe-vector-available",
  "failure-invalid-request",
  "failure-denied-profile",
  "failure-unavailable-command",
  "failure-timeout",
  "failure-aborted",
  "failure-launch-failed",
  "failure-nonzero-exit",
  "failure-malformed-output",
  "failure-output-limit",
  "reject-invalid-truth-tier",
  "reject-unsigned-skw-read-path",
  "reject-raw-read-path",
  "reject-qmd-read-path",
  "reject-unknown-profile",
  "reject-hidden-proposal",
  "reject-malformed-session-identity",
  "reject-cross-agent-session-identity",
  "reject-missing-openclaw-fields",
  "process-unavailable-command",
  "process-timeout",
  "process-abort",
  "process-malformed-json",
  "process-oversized-stdout",
  "process-nonzero-exit",
] as const;
